name: Build installers

on:
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install WiX Toolset 3.14
      run: choco install wixtoolset --version 3.14.0
      continue-on-error: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --no-restore --configuration Release

    - name: Build MSI Installer
      run: msbuild Scripture.Installer/Scripture.Installer.wixproj /p:Configuration=Release

    - name: Build Bundle Installer
      run: msbuild Scripture.Installer.Bundle/Scripture.Installer.Bundle.wixproj /p:Configuration=Release

    - name: Rename Installers
      run: |
        $timestamp = Get-Date -Format "yyyyMMdd-HHmm"
        Rename-Item "Scripture.Installer/bin/x64/Release/ScriptureAutocadPlugin.msi" -NewName "ScriptureAutocadPlugin-$timestamp.msi"
        Rename-Item "Scripture.Installer.Bundle/bin/x64/Release/ScriptureInstaller.exe" -NewName "ScriptureInstaller-$timestamp.exe"
      shell: pwsh

    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ScriptureAutocadPlugin
        path: ScriptureAutocadPlugin-$timestamp.msi

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ScriptureBundleInstaller
        path: ScriptureBundleInstaller-$timestamp.exe
