name: Create Release Zip

on:
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --no-restore --configuration Release

    - name: Prepare Directory for Zipping
      run: |
        $outputFolder = "ScripturePlugin"
        New-Item -ItemType Directory -Path $outputFolder
        Copy-Item -Path "./Scripture/bin/x64/Release/net8.0-windows/*" -Destination $outputFolder -Recurse

    - name: Create Zip Archive
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd-HH-mm"
        $zipName = "ScripturePlugin-$timestamp.zip"
        Compress-Archive -Path "./ScripturePlugin/*" -DestinationPath "./$zipName"

    - name: Upload Zip Archive
      uses: actions/upload-artifact@v3
      with:
        path: "./*.zip"
