name: Create Release Zip

on:
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --no-restore --configuration Release
  
    - name: Set timestamp
      id: set_timestamp
      run: echo "timestamp=$(date +'%y-%m-%d-%H-%M')" >> $GITHUB_ENV

    - name: Upload Zip Archive
      uses: actions/upload-artifact@v3
      with:
        name: ScripturePlugin-${{ env.timestamp }}
        path: "./Scripture/bin/x64/Release/net8.0-windows/*"


